# Generated by Django 3.2.20 on 2023-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_recipe_recipe_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
